### ISSUE TITLE
The docs for this library don't seem to exist?

### ISSUE THREAD

**Issue by hopkapi** [adafruit/Adafruit_CircuitPython_HDC302x#1]
The docs linked to via the Read the Docs link, give you a 404. Not sure if they just haven't been written yet, or if the link is broken?

[https://docs.circuitpython.org/projects/hdc302x/en/latest/](https://docs.circuitpython.org/projects/hdc302x/en/latest/)

**Comment by FoamyGuy** [comment]
Thanks for reporting. 

There is a small typo in the URL configuration for the docs to this library. You can view them currently here: https://docs.circuitpython.org/projects/hdx302x/en/latest/ (note "hdx" in the name instead of "hdc"). 

I've just tried to update the configuration to correct that a moment ago. I'm not entirely sure how long until the updated URL takes effect though. It may be live by the time you try again, but if not the link in this comment should work for the time being.

**Comment by FoamyGuy** [comment]
This is fixed now. thanks again.
